language: python
python:
    - "2.7"

sudo: false

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - texinfo
     - libgmp3-dev
     - libvtk5-dev
     - libvtk5.8
     - gcc-4.8
     - g++-4.8
     - clang

install:
    - wget http://sourceforge.net/projects/pluto-compiler/files/pluto-0.11.3.tar.gz
    - tar zxvf pluto-0.11.3.tar.gz
    - cd pluto-0.11.3
    - ./configure
    - make -j4
    - chmod +x polycc
    - export PATH=$PATH:`pwd`
    - export CXX="g++-4.8"
    - cd ..
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python setup.py build_clib --build-clib=`pwd`

script:
    - export PYTHONPATH=`pwd`:$PYTHONPATH
    - flake8 opesci
    - flake8 tests
    - export CC="g++-4.8"
    - python tests/eigenwave3d.py default --compiler=g++ --execute --nthreads=4
    - OMP_NUM_THREADS=4 tests/src/eigenwave3d
    - python tests/eigenwave3d.py default --compiler=g++ --output
    - python tests/eigenwave3d.py read --compiler=g++
    - python tests/eigenwave3d.py default --execute --compiler clang --nthreads=1
    - OMP_NUM_THREADS=1 tests/src/eigenwave3d
    - python tests/eigenwave3d.py default --output
    - python tests/eigenwave3d.py read
    - python tests/eigenwave3d.py default --compiler=g++ -so=8
    - OMP_NUM_THREADS=4 tests/src/eigenwave3d
    - python tests/eigenwave3d.py default --compiler=g++ --execute --nthreads=4 --pluto
    - OMP_NUM_THREADS=4 tests/src/eigenwave3d_pluto
    - python tests/eigenwave3d.py --output --pluto
    - python tests/eigenwave3d.py default --fission --compiler=g++ --execute --nthreads=4
    - python tests/simplewaveequation.py default
    - g++ tests/src/regular3d.cpp -lm
    - ./a.out
