#PBS -N opesci_codegen
#PBS -l walltime=1:00:00
#PBS -l select=1:ncpus=12:mem=1800mb

module load intel-suite/2015.1
# module load mpi
module load likwid

# Example of how to set environment flags
# export LIBS="-L/usr/X11R6/lib64/ -L${MKL_HOME}/lib/64/ -lmkl_intel_lp64 -lmkl_sequential -lmkl_core"

# Find the right directory
cd $PBS_O_WORKDIR

export OMP_NUM_THREADS=6

export KMP_AFFINITY="compact,verbose" 

likwid-topology > topology.log

./a.out > my.log
